trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  soapui_project_path: 'soapui-project-remove/CountryCurrencyProject-soapui-project.xml'
  soapui_install_dir: '$(Build.SourcesDirectory)/soapui'
  report_output_dir: '$(Build.ArtifactStagingDirectory)/soapui-reports'

stages:
- stage: RunSoapUITests
  displayName: 'Execute SoapUI Tests and Publish Report'
  jobs:
  - job: SoapUITests
    displayName: 'Run SoapUI Project'
    steps:

    # ✅ Explicitly install Java 11
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
      displayName: 'Install Java 11'

    # ✅ Verify Java is now Java 11
    - script: |
        echo "✅ Verifying Java version..."
        java -version
        echo "✅ JAVA_HOME is set to: $JAVA_HOME"
      displayName: 'Verify Java 11'

    # ✅ Download and extract SoapUI from SmartBear’s official S3
    - script: |
        echo "⬇️ Downloading SoapUI..."
        wget https://s3.amazonaws.com/downloads.eviware/soapuios/5.7.0/SoapUI-5.7.0-linux-bin.tar.gz
        mkdir -p $(soapui_install_dir)
        tar -xvzf SoapUI-5.7.0-linux-bin.tar.gz -C $(soapui_install_dir) --strip-components=1
      displayName: 'Download & Extract SoapUI'

    # ✅ Check project file exists
    - script: |
        echo "📁 Checking SoapUI project file:"
        ls -l "$(Build.SourcesDirectory)/$(soapui_project_path)"
      displayName: 'Check SoapUI Project File'

    # ✅ Run SoapUI Tests
    - script: |
        echo "🚀 Running SoapUI Project..."
        chmod +x $(soapui_install_dir)/bin/testrunner.sh
        $(soapui_install_dir)/bin/testrunner.sh "$(Build.SourcesDirectory)/$(soapui_project_path)" -s "CountryInfoServiceSoapBinding12 TestSuite" -r -j -f"$(report_output_dir)"
      displayName: 'Execute SoapUI Tests with Java 11'

    # ✅ Publish reports
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(report_output_dir)'
        artifactName: 'soapui-test-results'
        publishLocation: 'Container'
      displayName: 'Publish SoapUI Test Results'